{
  "formatVersion": "1.1",
  "component": {
    "group": "com.appsqueeze",
    "module": "ultimatemodule",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ultimatemodule-1.0.0.aar",
          "url": "ultimatemodule-1.0.0.aar",
          "size": 2267,
          "sha512": "721b6ce496ddfacce5ba6c7dd50dab117f565cb35b2d09a98d5f9b1e3f45d4acf96246c45abdc566ce6bda159d8d0ff0782253dea843e3c88e79e50ffd6b638c",
          "sha256": "255bf935f3ed6b1db5a17c629716634fcb9ae9b82f09e14847a74fb7e5caf0f5",
          "sha1": "5d4599eb8d7836c69ec594a9abaf2847347e91ba",
          "md5": "1d72ab8f8111f4af122b26bdd1585264"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ultimatemodule-1.0.0.aar",
          "url": "ultimatemodule-1.0.0.aar",
          "size": 2267,
          "sha512": "721b6ce496ddfacce5ba6c7dd50dab117f565cb35b2d09a98d5f9b1e3f45d4acf96246c45abdc566ce6bda159d8d0ff0782253dea843e3c88e79e50ffd6b638c",
          "sha256": "255bf935f3ed6b1db5a17c629716634fcb9ae9b82f09e14847a74fb7e5caf0f5",
          "sha1": "5d4599eb8d7836c69ec594a9abaf2847347e91ba",
          "md5": "1d72ab8f8111f4af122b26bdd1585264"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ultimatemodule-1.0.0-sources.jar",
          "url": "ultimatemodule-1.0.0-sources.jar",
          "size": 2289,
          "sha512": "cf657b9395a3686f182449116fd442864652b5fdd5d06bd37d135d33c7d92873dca1365d40b3f8b90ee17ab97deaf560079e6dbe87fe9ffbbb6600128cf733ef",
          "sha256": "5e783c7c8e9b555d67b591902a761646102b47304261665d56aa525378e814b3",
          "sha1": "47505c791e725484870eb35b588c88e0aae8c2db",
          "md5": "0036fff3a544f0270ccf7480b3e48f57"
        }
      ]
    }
  ]
}
